paths:
  train: train.csv
  test: test.csv

target:
  column: forward_returns
  drop_columns: [date_id]
  categorical: []

cv:
  n_splits: 5
  shuffle: false
  random_state: 42

model:
  params:
    objective: regression
    metric: rmse
    learning_rate: 0.01
    num_leaves: 64
    feature_fraction: 0.8
    bagging_fraction: 0.8
    bagging_freq: 1
    min_data_in_leaf: 20
    verbosity: -1

training:
  num_boost_round: 2000
  early_stopping_rounds: 200
  eval_period: 100

logging:
  directory: ./log
